"""create_wishlists_table

Revision ID: 484828734e4e
Revises: 5b1757ace65a
Create Date: 2026-05-20 14:13:46.645075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '484828734e4e'
down_revision: Union[str, Sequence[str], None] = '5b1757ace65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('buyer_id', app.core.database.GUID(), nullable=False),
    sa.Column('product_id', app.core.database.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buyer_id', 'product_id')
    )
    op.create_index(op.f('ix_wishlists_buyer_id'), 'wishlists', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_wishlists_product_id'), 'wishlists', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_product_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_buyer_id'), table_name='wishlists')
    op.drop_table('wishlists')
    # ### end Alembic commands ###
